/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package management;

/**
 *
 * @author Shovo
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        newb = new javax.swing.JButton();
        newbook = new javax.swing.JButton();
        issue = new javax.swing.JButton();
        ret = new javax.swing.JButton();
        sta = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("jButton2");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5356, 2567, -1, -1));

        jButton3.setText("jButton3");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5586, 2567, -1, -1));

        jButton4.setText("jButton4");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5667, 2567, -1, -1));

        jButton5.setText("jButton5");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5905, 2567, -1, -1));

        jButton6.setText("jButton6");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6121, 2567, -1, -1));

        newb.setBackground(new java.awt.Color(204, 255, 204));
        newb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        newb.setForeground(new java.awt.Color(255, 51, 0));
        newb.setText("New Student");
        newb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbActionPerformed(evt);
            }
        });
        getContentPane().add(newb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 158, 60));

        newbook.setBackground(new java.awt.Color(204, 255, 204));
        newbook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        newbook.setForeground(new java.awt.Color(255, 51, 0));
        newbook.setText("New Book");
        newbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbookActionPerformed(evt);
            }
        });
        getContentPane().add(newbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 158, 60));

        issue.setBackground(new java.awt.Color(204, 255, 204));
        issue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        issue.setForeground(new java.awt.Color(255, 51, 0));
        issue.setText("Issue Book");
        issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueActionPerformed(evt);
            }
        });
        getContentPane().add(issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 158, 60));

        ret.setBackground(new java.awt.Color(204, 255, 204));
        ret.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ret.setForeground(new java.awt.Color(255, 51, 0));
        ret.setText("Return Book");
        ret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retActionPerformed(evt);
            }
        });
        getContentPane().add(ret, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 158, 60));

        sta.setBackground(new java.awt.Color(204, 255, 204));
        sta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sta.setForeground(new java.awt.Color(255, 51, 0));
        sta.setText("Statistics");
        sta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staActionPerformed(evt);
            }
        });
        getContentPane().add(sta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 158, 60));

        logout.setBackground(new java.awt.Color(204, 255, 204));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 51, 0));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 158, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/management/hans-jurgen-weinhardt-FZ5nx86tP2U-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
       //setVisible(false);
       new login().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void newbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbActionPerformed
new newstudent1().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_newbActionPerformed

    private void newbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbookActionPerformed
new newbook().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_newbookActionPerformed

    private void issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueActionPerformed
new issue().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_issueActionPerformed

    private void retActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retActionPerformed
new returnbook().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_retActionPerformed

    private void staActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staActionPerformed
new statistics().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_staActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton issue;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton newb;
    private javax.swing.JButton newbook;
    private javax.swing.JButton ret;
    private javax.swing.JButton sta;
    // End of variables declaration//GEN-END:variables
}
