/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package management;

/**
 *
 * @author Shovo
 */
import  java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import project.connectionprovider;
public class issuebook extends javax.swing.JFrame {

    /**
     * Creates new form issuebook
     */
    Connection con;
    PreparedStatement pst;
    public issuebook() {
        initComponents();
        //connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtb = new javax.swing.JTextField();
        txts = new javax.swing.JTextField();
        txti = new com.toedter.calendar.JDateChooser();
        txtd = new com.toedter.calendar.JDateChooser();
        issue = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Book ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 129, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Student ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 185, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Issue Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 243, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 334, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Due Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 306, -1, -1));

        txtb.setBackground(new java.awt.Color(255, 255, 51));
        txtb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtb, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 123, 201, -1));

        txts.setBackground(new java.awt.Color(255, 255, 51));
        txts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txts, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 179, 201, -1));

        txti.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txti, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 237, 201, -1));
        getContentPane().add(txtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 306, 201, -1));

        issue.setBackground(new java.awt.Color(153, 255, 153));
        issue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        issue.setText("Issue");
        issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueActionPerformed(evt);
            }
        });
        getContentPane().add(issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 381, -1, -1));

        close.setBackground(new java.awt.Color(51, 255, 153));
        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 381, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/management/hans-jurgen-weinhardt-FZ5nx86tP2U-unsplash.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueActionPerformed
    
        SimpleDateFormat d=new SimpleDateFormat();
     String Book_ID=txtb.getText();
     String Student_ID=txts.getText();
     String Issue_Date=d.format(txti.getDate());
     String Due_Date=d.format(txtd.getDate());
     String Return_Book="No";
   try{
        con=connectionprovider.getcon();
         pst=con.prepareStatement("insert into issue(Book_ID,Student_ID,Issue_Date,Due_Date,Return_Book)values(?,?,?,?,?)");
         ResultSet rs=pst.executeQuery("select *from book where Book_ID='"+Book_ID+"'");
         if(rs.next()){
            ResultSet rs1=pst.executeQuery("select *from student where Student_ID='"+Student_ID+"'");
            if(rs1.next()){
              pst.setString(1, Book_ID);
              pst.setString(2, Student_ID);
              pst.setString(3, Issue_Date);
              pst.setString(4,Due_Date);
              pst.setString(5, Return_Book);
              pst.executeUpdate();
              
             JOptionPane.showMessageDialog(null, "Book successfully issued");
             setVisible(false);
             new issuebook().setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(null, "incorrect student id");
         }
         else{
            JOptionPane.showMessageDialog(null, "incorrect Book_ID"); 
         }
   }
          
         
     catch(Exception e){
          System.out.println(e);
     }
    }//GEN-LAST:event_issueActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
      System.exit(0);  // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issuebook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JButton issue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtb;
    private com.toedter.calendar.JDateChooser txtd;
    private com.toedter.calendar.JDateChooser txti;
    private javax.swing.JTextField txts;
    // End of variables declaration//GEN-END:variables
}
