/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package management;

/**
 *
 * @author Shovo
 */
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.jshell.JShellException;
import net.proteanit.sql.DbUtils;
import project.connectionprovider;
public class newstudent1 extends javax.swing.JFrame {

    /**
     * Creates new form newstudent
     */
      Connection con=null;
    PreparedStatement pst=null;
    ResultSet r=null;

    public newstudent1() {
        initComponents();
     Connect();
    insert();
    }
 public void insert(){
     String q="select *from student";
     try{
         pst=con.prepareStatement(q);
         ResultSet r=pst.executeQuery();
         tab1.setModel(DbUtils.resultSetToTableModel(r));
     }catch(Exception e){
         JOptionPane.showMessageDialog(null, e);
     }
 }
        public void Connect(){
        
        
        try {
            
            
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(newstudent1.class.getName()).log(Level.SEVERE, null, ex);
            }
            

            
            con=DriverManager.getConnection("jdbc:mysql://localhost/newstudent","root","");
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(newstudent1.class.getName()).log(Level.SEVERE, null, ex);
        }
      
       

}    
           
            
            
            
            
         
            
            
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcn = new javax.swing.JComboBox<>();
        txtbn = new javax.swing.JComboBox<>();
        txtf = new javax.swing.JTextField();
        txtn = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        close = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab1 = new javax.swing.JTable();
        del = new javax.swing.JButton();
        ed = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Student ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 91, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("Father Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 51, 0));
        jLabel4.setText("Course Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 51, 0));
        jLabel5.setText("Branch Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        txtcn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSC" }));
        getContentPane().add(txtcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 220, 40));

        txtbn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtbn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "CSE", "EEE", "Civil", "Mechanical" }));
        getContentPane().add(txtbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 220, 40));

        txtf.setBackground(new java.awt.Color(255, 255, 102));
        txtf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 220, 40));

        txtn.setBackground(new java.awt.Color(255, 255, 102));
        txtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 220, 40));

        txtid.setBackground(new java.awt.Color(255, 255, 102));
        txtid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 30, 220, 40));

        close.setBackground(new java.awt.Color(204, 204, 204));
        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 437, -1, 40));

        save.setBackground(new java.awt.Color(204, 204, 204));
        save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 437, -1, 40));

        tab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student_ID", "Name", "Father_Name", "Course_Name", "Branch_Name"
            }
        ));
        jScrollPane1.setViewportView(tab1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 26, 490, 380));

        del.setBackground(new java.awt.Color(204, 204, 204));
        del.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        getContentPane().add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 463, 80, 40));

        ed.setBackground(new java.awt.Color(204, 204, 204));
        ed.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ed.setText("Edit");
        ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edActionPerformed(evt);
            }
        });
        getContentPane().add(ed, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 463, 80, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/management/hans-jurgen-weinhardt-FZ5nx86tP2U-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
setVisible(false);      // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try{
          String Student_ID=txtid.getText();
          String Name=txtn.getText();
          String Father_Name=txtf.getText();
          String Course_Name=(String)txtcn.getSelectedItem();
          
          String Branch_Name=(String)txtbn.getSelectedItem();
          Connection con=connectionprovider.getcon();
          pst=con.prepareStatement("insert into student(Student_ID,Name,Father_Name,Course_Name,Branch_Name)values(?,?,?,?,?)");
          pst.setString(1, Student_ID);
          pst.setString(2, Name);
          pst.setString(3, Father_Name);
          pst.setString(4, Course_Name);
          pst.setString(5, Branch_Name);
          pst.executeUpdate();
          JOptionPane.showMessageDialog(this, "successfully saved");
         /* txtid.setText("");
          txtname.setText("");
          txtfname.setText("");
          txtcname.setSelectedIndex(-1);
          txtbname.setSelectedIndex(-1);*/
        }catch(Exception e){
            System.out.println(e);
        }
        insert();
        setVisible(false);
        new newstudent1().setVisible(true);
    }//GEN-LAST:event_saveActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
       String v1=txtid.getText();
       String q="delete from student where Student_ID='"+v1+"'";
       try{
           pst=con.prepareStatement(q);
           pst.execute();
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Deleted");
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
       setVisible(false);
       new newstudent1().setVisible(true);
    }//GEN-LAST:event_delActionPerformed

    private void edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edActionPerformed
        String v1=txtid.getText();
        String v2=txtn.getText();
        String v3=txtf.getText();
        String v4=(String)txtcn.getSelectedItem();
        String v5=(String)txtbn.getSelectedItem();
        String q="update student set Student_ID='"+v1+"',Name='"+v2+"',Father_Name='"+v3+"',Course_Name='"+v4+"',Branch_Name='"+v5+"' where Student_ID='"+v1+"'";
        
        try{
            pst=con.prepareStatement(q);
            pst.execute();
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"updated");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        setVisible(false);
        new newstudent1().setVisible(true);
    
    }//GEN-LAST:event_edActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newstudent1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newstudent1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newstudent1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newstudent1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newstudent1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JButton del;
    private javax.swing.JButton ed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton save;
    private javax.swing.JTable tab1;
    private javax.swing.JComboBox<String> txtbn;
    private javax.swing.JComboBox<String> txtcn;
    private javax.swing.JTextField txtf;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtn;
    // End of variables declaration//GEN-END:variables
}
